### PR TITLE
feat: Add logout and logoutAll for Oauth

### PR DESCRIPTION
**Pull request by to-Gabriel**
Follow up for PR #5 
Logout and LogoutAll routes allow for closing sessions.

Next is delete users to close out Oauth.

### CODE REVIEW

**Comment by to-Gabriel** [comment]
Delete user route added from PR #7 (already merged into this branch) this PR will close out Oauth.
Next is testing these routes, then Oauth2 functionality.

**Review by JaedonSpurlock01 — APPROVED** [review]
This looks good. How would the onboarding process work with your api?

How it previously worked with the older platform is that the user creates an account, and there was a "OnboardingNotCompleted" tag on the user object. If that was false, then every page route would redirect to the onboarding page (through middleware).

How would you apply this to our new platform? ViteJS does not provide as much support for middleware as it did with NextJS so the process may need to be adjusted.

**Comment by JaedonSpurlock01** [comment]
A potential workaround is that we could avoid the onboarding page all-together and just move its details to the create-account page.

Some details include, Name, Major, Branch, etc.

**Comment by to-Gabriel** [comment]
That sounds good to me, a registering should have the onboarding info asked.

**Pull request merged**
